package model

import (
	"sync"

	jwt "github.com/dgrijalva/jwt-go"
)

//User - The user details struct (Contains everything about the user)
type User struct {
	Email            string `json:"email"`
	Password         string `json:"password"`
	FullName         string `json:"full_name"`
	Address          string `json:"address"`
	PhoneNumber      string `json:"phone_number"`
	VerificationCode string `json:"verification_code"`
}

//JwtClaim - The structure for the jwt token that gets hashed
type JwtClaim struct {
	Email string `json:"email"`
	jwt.StandardClaims
}

//TwilioCode - the code and timestamp generated by user registration
type TwilioCode struct {
	Code      string `json:"code"`
	TimeStamp string `json:"timestamp"`
}

//UserCodeMapping - a mapping provided between user, the code generated and the timestamp of the code generated
type UserCodeMapping struct {
	UserCodeMap map[string]TwilioCode
	Mux         sync.Mutex
}
